<a href="https://colab.research.google.com/github/CodeWithSridhar/Innomatics-Internship/blob/main/Task_6_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **Assignment:**
 **Task - 6 (Numpy - Both for Basic and Adv User)**

Questions Link:  https://www.hackerrank.com/domains/python?filters%5Bsubdomains%5D%5B%5D=numpy 

## Arrays

In [ ]:
import numpy

def arrays(arr):
    numpy_array = numpy.array(arr, float)
    return numpy_array[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

In [ ]:
import numpy
A = numpy.array(input().split(),int)
A = A.reshape(3,3)
print(A)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [2]:
import numpy
N,M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int) 
print(A.transpose())
print(A.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate

In [4]:
import numpy
P,N,M = map(int, input().split())
A = numpy.array([input().split() for _ in range(P)],int)
B = numpy.array([input().split() for _ in range(N)],int)
C = numpy.concatenate((A,B),axis = 0)
print(C)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
