<a href="https://colab.research.google.com/github/CodeWithSridhar/Innomatics-Internship/blob/main/Task_6_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **Assignment:**
 **Task - 6 (Numpy - Both for Basic and Adv User)**

Questions Link:  https://www.hackerrank.com/domains/python?filters%5Bsubdomains%5D%5B%5D=numpy 

## Arrays

In [ ]:
import numpy

def arrays(arr):
    numpy_array = numpy.array(arr, float)
    return numpy_array[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

In [ ]:
import numpy
A = numpy.array(input().split(),int)
A = A.reshape(3,3)
print(A)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [ ]:
import numpy
N,M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int) 
print(A.transpose())
print(A.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate

In [ ]:
import numpy
P,N,M = map(int, input().split())
A = numpy.array([input().split() for _ in range(P)],int)
B = numpy.array([input().split() for _ in range(N)],int)
C = numpy.concatenate((A,B),axis = 0)
print(C)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [ ]:
import numpy

A = tuple(map(int, input().split()))
print(numpy.zeros(A, int))
print(numpy.ones(A, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity

In [ ]:
import numpy
N,M = map(int, input().split())
print(numpy.eye(N,M))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array Mathematics

In [ ]:
import numpy
N,M = map(int, input().split())
A = numpy.array([list(map(int, input().split())) for n in range(N)])
B = numpy.array([list(map(int, input().split())) for n in range(N)])

print(numpy.add(A,B))
print(numpy.subtract(A,B))
print(numpy.multiply(A,B))
print(numpy.divide(A,B))
print(numpy.mod(A,B))
print(numpy.power(A,B))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0.2        0.33333333 0.42857143 0.5       ]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint

In [ ]:
import numpy
A = numpy.array(list(map(float, input().split())))
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


## Sum and Prod

In [ ]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
Sum = numpy.sum(A,axis = 0)
Prod = numpy.prod(Sum,axis = 0)
print(Prod)

2 2
1 2
3 4
24


## Min and Max

In [ ]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
Min = numpy.min(A,axis = 1)
print(numpy.max(Min))


4 2
2 5
3 7
1 3
4 7
4


## Mean, Var, and Std

In [ ]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.mean(A,axis = 1))
print(numpy.var(A,axis = 0))
numpy.set_printoptions(legacy='1.13')
print(numpy.std(A))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


## Dot and Cross

In [ ]:
import numpy
N = int(input())
A = numpy.array([input().split() for _ in range(N)], int)
B = numpy.array([input().split() for _ in range(N)], int)
print(numpy.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Inner and Outer

In [1]:
import numpy
A = numpy.array(input().split(),int)
B = numpy.array(input().split(),int)
print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


## Polynomials

In [2]:
import numpy
A,B,C = map(float, input().split())
X = int(input()) 
print(numpy.polyval([A,B,C],X))

1.1 2 3
0
3.0


## Linear Algebra

In [3]:
import numpy
N = int(input()) 
A = numpy.array([input().split() for _ in range(N)],float)
# Output needs to be round to 2 decimal points
print(round(numpy.linalg.det(A),2))

2
1.1 1.1
1.1 1.1
0.0
